version: "3.3"

services:
  api:
    build:
      context: .
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - migrations
    volumes:
      - ./.docker_env:/app/.env
  migrations:
    build:
      context: .
    depends_on:
      - postgres
    volumes:
      - ./.docker_env:/app/.env
    command: python manage.py migrate
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todolist
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres-data:/var/lib/postgresql/data