version: "2.1"

services:
  front:
    image: sermalenk/skypro-front:lesson-38
    ports:
      - 8034:80
    depends_on:
      - api
  api:
    image: deusprotiv/todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    depends_on:
      postgres:
        condition: service_healthy
#      migrations:
#        condition:
      migrations:
        condition: service_healthy #service_completed_successfully
    volumes:
      - ./.env:/app/.env
  migrations:
    image: deusprotiv/todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "ls"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./.env:/app/.env
    command: python manage.py migrate
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todolist
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
